### ISSUE TITLE
Trying the API for CreateCourseSection results in the following error.

### ISSUE THREAD

**Issue by davidkartuzinski** [open-apprentice/ellie-platform#3]
```
Class 'schemas.courses.CreateCourseSection' is not mapped
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/fastapi/routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/fastapi/routing.py", line 154, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/./main.py", line 107, in create
    db.add(to_create)
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2568, in add
    util.raise_(
  File "/Users/david/Desktop/OpenApprentice/repo/ellie2/ellie/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'schemas.courses.CreateCourseSection' is not mapped
```

**Comment by davidkartuzinski** [comment]
This whole class and model and how it relates to courses needs work. @bbelderbos

**Comment by bbelderbos** [comment]
Yes we need to fix relations.
I added some comments here: https://github.com/open-apprentice/ellie-platform/pull/4/files

HTH
Bob
